### ISSUE TITLE
Installation fails on 4.2.2

### ISSUE THREAD

**Issue by hermannkm** [momibun926/redmine_team_resource#4]
Getting

```
rake aborted!
NameError: uninitialized constant Date::Holidays
/var/www/redmine-4.2/plugins/redmine_team_resource/init.rb:5:in `<class:Date>'
```

**Comment by momibun926** [comment]
Hi, @hermannkm 
Thank you for reporting.
There were some unneeded gem references left. I have removed them, so please check the latest main branch.

**Comment by hermannkm** [comment]
Installation now working flawlessly.
