### ISSUE TITLE
Enhancement: short menu title

### ISSUE THREAD

**Issue by hermannkm** [momibun926/redmine_team_resource#6]
My menu is rather long (Additionals plugin) so the Title of your plugin eats up more space: Could there be an option for a short title?

**Comment by momibun926** [comment]
hi, @hermannkm 
There is no option, but I'll change it if you have a preferred title.

**Comment by hermannkm** [comment]
How about TRM :-)?

**Comment by momibun926** [comment]
OK, please wait few minute.

**Comment by momibun926** [comment]
I just pushed main branch. change to small title.

**Comment by hermannkm** [comment]
Thank you, pulled it, very nice!
